### ISSUE TITLE
Multi hard drive support

### ISSUE THREAD

**Issue by IPNugget** [tjmarkham/win10widgets#123]
with desktops and even laptops now commonly having more hard drives and ssds. having multi hard drive monitoring would be very nice to see

**Comment by MinhThienDX** [comment]
You mean multiple hard drive for the skin **Performance - Combo** or the skin **Performance - Disk**?

**Comment by IPNugget** [comment]
yes exactly

**Comment by benjaminshell** [comment]
I solved this by copying the Win10 Widgets folder multiple times in the Skins folder. To make it simple on myself I only kept the skins that I want. It's not the most elegant solutions but it works well.
![image](https://user-images.githubusercontent.com/17329101/57025074-c9e98b00-6bfb-11e9-9bdb-147f5b070de8.png)
![image](https://user-images.githubusercontent.com/17329101/57025162-04532800-6bfc-11e9-88be-1de8ebe36e4c.png)

**Comment by Beguiled** [comment]
You can also accomplish this by simply duplicating HardDrive (in Windows Explorer), refreshing your skin details, and loading the version (Large/Medium/Small) you prefer. Then right-click the new meter and select the drive it should be targeting. This is a little less cumbersome that duplicating the entire skin package.
![image](https://user-images.githubusercontent.com/7060159/57025772-1df96d00-6c06-11e9-8789-f71a2166df04.png)

**Comment by IPNugget** [comment]
Thank you very much for your help. I very much appreciate it. You don't get
this kind of help from most indie devs, so major props to you

**Comment by MinhThienDX** [comment]
Hey @benjaminshell, where is your E drive? Just curious 😂

**Comment by MinhThienDX** [comment]
@IPNugget I guess this issue is solved, right?
If so, could you kindly close this issue?
