### ISSUE TITLE
Weather widget nor working "connection error"

### ISSUE THREAD

**Issue by Weather2020** [tjmarkham/win10widgets#134]
Since yesterday, I am unable to get the weather updated with the refresh. It always returns with connection error. Anyone facing the same problem.

Can some expert help on this? 

I am only a user and do not know much about the language and hope that some one can help here.

Thank you

Simon

**Comment by Weather2020** [comment]
![050620203](https://user-images.githubusercontent.com/66459606/83866077-d2df5100-a759-11ea-9106-8fbfa5515b23.png)

**Comment by MinhThienDX** [comment]
This repo is abandoned, please take a look at this https://github.com/MinhThienDX/win10widgets/issues/27
