### ISSUE TITLE
I fixed SPOTIFY skin and translated some skins in italian

### ISSUE THREAD

**Issue by MrMdn5** [tjmarkham/win10widgets#139]
Hi guys, i fixed spotify skin and translated some skins in italian, if someone is interessed please write to me. Oh, and sorry for my bad English
![Screenshot (59)](https://user-images.githubusercontent.com/50810626/89544036-ee221780-d801-11ea-9ee6-40d73ca6c540.png)

**Comment by MrMdn5** [comment]
I can also translate every skin in every language. Example in italian in the photo.
![Screenshot (61)](https://user-images.githubusercontent.com/50810626/89544472-77394e80-d802-11ea-84f9-7935232b31d5.png)

**Comment by That1neGuy** [comment]
Hi, I would be interested in the fixed Spotify skin. If you could share the .rmskin or any extra lines of code that you added to the existing skins, that would be appreciated. Good to know someone was able to fix it.

**Comment by MinhThienDX** [comment]
Hello there @Mariodn775, would you kindly open a pull request on https://github.com/MinhThienDX/win10widgets?
As you see, this repo is inactive for a very long time.

**Comment by MrMdn5** [comment]
someone is still interessed? i returned just now on github

**Comment by 66Bunz** [comment]
> someone is still interessed? i returned just now on github

I am

**Comment by MrMdn5** [comment]
> > someone is still interessed? i returned just now on github
> 
> I am


[Spotify.zip](https://github.com/tjmarkham/win10widgets/files/5937153/Spotify.zip)
Here's the file edited with the fix. You need to install the WebNowPlaying plugin and build a modded spotify through spicetify. Youu can't use the Windows Store edition of spotify, so you need to download it from their web site. For any answer, just reply.
