### ISSUE TITLE
Performance disk widget - Showing 0% disk time

### ISSUE THREAD

**Issue by Bogeyx** [tjmarkham/win10widgets#16]
I have 3 Disks (1SSD, 2HDDs all GPT), but the widgets shows always 0% workload for all of them. The Task Manager can display real values.
Works perfectly with my other PC (2HDDs both MBR).

**Comment by tjmarkham** [comment]
Thanks for the feedback!

The disk widget retrieves information directly from the Windows Performance Monitor (different than the Task Manager) so the problem might be with the Performance Monitor, in which case there's not much I can do about it.

Would you mind checking the Performance Monitor and letting me know what you see? Add all the instances of the LogicalDisk object and let me know what you see. For good measure, do all the instances of the PhysicalDisk object as well.

To do this, simply open the Performance Monitor application, click "Performance Monitor" in the left section (under "Monitoring Tools"), and click the green "plus" icon. In the window that comes up, the top area of the left section is where you select your objects (e.g. LogicalDisk or Physical Disk) and the bottom area of the left section is where you select the instances of the object (e.g. <All instances>).

**Comment by pattshaw182** [comment]
Having the same issue, running Windows 10.

**Comment by tjmarkham** [comment]
Thanks for the feedback pattshaw182!

Can you follow the steps outlined above and report back? I appreciate you letting me know there's an issue, but I can't do much without more info.

**Comment by pattshaw182** [comment]
So I found the issue for me. My Performance Monitor wasn't loaded correctly.  Had to do the following:
-------------------------------------------------------------------------------------------------------------
"Click Start, type cmd right click cmd.exe, and select Run as administrator.
At the prompt, type lodctr /r and press ENTER. This will repair the pointers (those are stored in the registry).
Result:
C:\Windows\system32>lodctr /r
Info: Successfully rebuilt performance counter setting from system backup store"
--------------------------------------------------------------------------------------------------
Had to do this twice for it to rebuild correctly, then restarted Rainmeter.  Now its working fine.

**Comment by tjmarkham** [comment]
Wow! Thank you for that info! Very helpful, you're awesome :)

**Comment by tjmarkham** [comment]
Since this seems to be a Performance Monitor issue, I'm going to close this issue and mark it as "can't fix." If new information comes to light that indicates there's something I can do on my end, it will be re-opened.
