### ISSUE TITLE
Weather Widget Not Showing Data, Only Says Refresh In Several Seconds

### ISSUE THREAD

**Issue by CaseyKazan** [tjmarkham/win10widgets#20]
Hi, again. I also am unable to get the Win10 Widgets\Weather to work. I have tried all five sizes and I never see any data, just a message to refresh in several seconds.

I'm using Rainmeter 4.0.0.0 beta r2613 64-bit (Jul 6 2016).

I don't think I've received the Aug 2, 2016 Windows 10 update yet (unless that is the Security Update for Microsoft ASP.NET MVC 4.0 (KB2993928) item in my update history).

However, this has been going on since I installed Rainmeter last month.

**Comment by tjmarkham** [comment]
Did you try changing the weather location?

**Comment by CaseyKazan** [comment]
Oh, that fixed it.  It is something that is not in the basic help and not intuitive.  I suggest adding a settings icon to the weather widget.  Thank you for responding.  This is now closed.

**Comment by tjmarkham** [comment]
> It is something that is not in the basic help

What "basic help" are you referring to? Because it's in both the intro video: https://youtu.be/TPvjfNErIMc?t=110 and the the **Welcome-Intro.txt** file you can access from the Welcome widget (see line 182 in the "Widget Options" section).

> not intuitive. I suggest adding a settings icon to the weather widget.

Not to be rude, but having settings in the right-click menu is about as intuitive as it gets. When you need to modify the settings of something in Windows, what do you do? You right-click it. If you look around the Windows operating system, you'll notice there are plenty of items with right-click menus that don't have settings icons. It's understood that users will use the right-click menu to access settings.

**Comment by CaseyKazan** [comment]
TJ: RELAX:  you're young and apparently a bit defensive about your product.  I did not attack you.  I did not say win10widgets is bad.  I said your help fixed my issue, and thanked you for responded and commented on how *I* felt about a particular aspect of the app. Okay?  I'm on YOUR side.

While I'm not an expert by any means, I have been using computers since back in the days of teletype connections and bubbling in FORTRAN cards, and have owned PCs since the late '80s.  And some of the things with win10widgets are not obvious or intuitive.  Do you really want to make this more user friendly?  Then read this--I actually do consulting on website and software end-user friendliness, okay? 

In the video you mentioned--which is only an introduction to the product because a video is cumbersome for the user to refer to regarding actual functionality.  One watches it (maybe) just to see what's in a product, NOT for how to use it. l That's the difference between an intro video and an instructional video which IS a how-to.

Your intro video shows the CURSOR moving over the weather skin (Rainmeter's odd terminology for what you and everybody else would call a widget) and you saying "The weather widget allows you to go into custom skin actions...." and "I'll show you this option now..."  Left-click to access?  Right-click?  You don't say this in your video and there is not a little gear icon or three horizontal dot icon or three stacked little horizontal dash icon to indicate "click here for weather widget settings" to make this OBVIOUS.   Okay?  So that's BOTH of the things that *I* felt would be nice additions.

So it doesn't just "work automatically" then, does it?  The user has to at least KNOW that they have to enter either locate automatically or their ZIP code or city.  Just seeing "refresh" indicates that something isn't working, not that something isn't setup right.  So, how about making the weather widget default to automatic?  Or when it first is loaded, if it hasn't been used before, the settings menu pops open OR in the widget, the options for automatic or manual location settings appear as options or buttons?  Because everything else in win10widgets DOES work immediately and that's great.  I have it running all the time using a dual monitor setup and it's info that I use all the time.

Regarding "help," what was confusing to me, until later yesterday, is that win10widgets and Rainmeter aren't the same thing so I was referring to their help which is about Rainmeter and not about your widgets.

Your Welcome widget shows the video and then in ordinary sized text (the same font size as the reset of the text in the Welcome widget) "click here to read about it."  Well, that does not make clear that by clicking it, you actually see the actual HELP on how to use win10widgets!  And LOTS of people never watch intro vidoes.  By putting that on the widget, on something that users will TURN OFF after the first time or two, that "click here" access is GONE.  The "help" button that a user sees when they left click on the Rainmeter icon in the taskbar or in the Manage Rainmeter window, only goes to Rainmeter.  So once your Welcome widget is unloaded, how is a user to know that there is useful information in how to use your app buried inside of it?  Make it OBVIOUS, the same way that the Rainmeter help access is obvious.  Why not, on the welcome screen, make a line that says "Click here for the win10widgets how-to text file." and put it in BOLD face or something to make it stand out?  Just saying "welcome" doesn't say "this is the only place to see text on how to use win10widgets."  And perhaps change the name of the Welcome skiin and welcome.ini to WelcomeAndHelp?  Or WelcomeHelp?  Just something to identify it as something more than an ordinary welcome screen where users can find actual help.

Also: on YOUR webpage, why not add a section that says HELP and tells (potential) users where it is located?  Or include this information under CONTACT AND SUPPORT?

Lastly, and I'm posting this in the Rainmeter forum, one way or another, either THEY need to rename "skins" to "widgets", or YOU need to start identifying the individual components in win10widgets as skins the way that Rainmeter does.  YOU do it correctly, they don't, but it need to be coordinated to avoid confusion.   That's like one company calling a car's manual gear shift lever the "transmission modifying device."  You see what I mean?  So, either you get them to call the components in the skins (whether illustro or Win10 Widgets or whatever) "widgets" and not "skins" OR you start calling your actual widgets "skins" (ick, but one or the other).

Best wishes with continued support of win10widgets, college and whatever else you're up to.

**Comment by tjmarkham** [comment]
I'm plenty relaxed; I was simply being direct. You said you thought the right-click menu wasn't intuitive, I said I thought it was and explained my reasoning.

I don't think you're "attacking" anything and therefore don't feel defensive. On the contrary, you seem to have interpreted my response as an "attack" of some sort and you have gotten incredibly defensive (explaining your background, delving into semantics between "intro" and "how-to" videos, using random capitalized words, etc.). By attributing the "deffensive" and "attacked" qualities to me, while exhibiting them yourself, it would appear that you are [projecting](https://en.wikipedia.org/wiki/Psychological_projection).

> So it doesn't just "work automatically" then, does it? The user has to at least KNOW that they have to enter either locate automatically or their ZIP code or city. Just seeing "refresh" indicates that something isn't working, not that something isn't setup right. So, how about making the weather widget default to automatic?

The Weather widget is set to "auto-locate" by default. It shouldn't show the "refresh" button initially; what you've experienced is a bug. If you had read the threads I linked to where another user had a similar issue, you would have seen that. Here are the links again:

Thread: https://github.com/tjmarkham/win10widgets/issues/7
Comment: https://github.com/tjmarkham/win10widgets/issues/7#issuecomment-236367185

> LOTS of people never watch intro vidoes [sic]

You have a pattern of blame-shifting; take some personal responsibility. Didn't watch the intro video? Didn't read the website? Didn't read the intro text file? Don't be surprised when you can't figure something out. I provided abundant resources in multiple formats but I can't make you watch/read them, that's up to you. The saying: "you can lead a horse to water, but you can't make it drink" comes to mind.

I appreciate your feedback. We can agree to disagree, it's not the end of the world.

**Comment by tjmarkham** [comment]
> Lastly, and I'm posting this in the Rainmeter forum, one way or another, either THEY need to rename "skins" to "widgets", or YOU need to start identifying the individual components in win10widgets as skins the way that Rainmeter does. YOU do it correctly, they don't, but it need to be coordinated to avoid confusion. That's like one company calling a car's manual gear shift lever the "transmission modifying device." You see what I mean? So, either you get them to call the components in the skins (whether illustro or Win10 Widgets or whatever) "widgets" and not "skins" OR you start calling your actual widgets "skins" (ick, but one or the other).

Please do not post on the Rainmeter forum; they are not going to stop calling them skins.

In the same vein, I'm not going to stop calling them widgets.

No one *needs* to do anything... You're taking this a little too seriously. These aren't companies, these are just regular people making free software tools for other to use. You didn't buy anything, so you don't really have any room to make these types of demands. If you don't like it, you don't have to use it.

**Comment by CaseyKazan** [comment]
TJ:

1) Caps are used for emphasis--one could also use asterisks.  I wasn't typing in all-caps, and very few of my words were capitalized.

2) It isn't "blame shifting" it's pointing out, and I'm going to do it here, COMMON HUMAN BEHAVIOR.  Not just mine, but lots of people.  Do you ever read TOUs?  But you agree to them all the time, right?  Similarly, lots of people never look at intro videos or intro screens and rely on words like "automatic" and "no setup involved" for hardware, software, consumer electronics, sporting goods, etc. for better or worse.  Lots of people don't read manuals, whether in print, in a file, or on the web, or even on-screen help dialogues.  Lots of people are completely incapable of doing even a basic web search for their issue or where to find help for it.  That is why things need to be obvious and easy to find.  The question is whether you want win10widgets to be for experts (like you) who know things like coding and would tinker around with precise x- and y-coordinates for positioning the widgets, for experienced but non-experts (like me) who like to customize their computer and keep up with software (and firmware) updates and drivers, and "hacking" their way through Win 10 BS regarding administrator rights, for average users who want to try out something interesting (like your app), or for ANYBODY at all.

YOU are seeing your app from your point of view without taking all of this into account.  What you think is obvious and apparent to a typical user isn't.  I wasn't even exactly clear on the difference between Rainmeter--the underlying software--and your app (which I now understand is like the difference between a browser and an extension).  I just saw something on Lifehacker or somewhere, it sounded like a cool app (and like I said, I was running Windows Task Manager all the time and that isn't exactly customizable), so I downloaded and installed it.  As an end-user, believing this to be a non-IT professional-targeted app, going to GitHub (which I was already a member and really isn't geared towards average users like me but for people who code) to see if there is an existing bug report is something they would NEVER do. They wouldn't even understand that such things exist or know what to do with the information or how to try and solve things on a coding level (I definitely cannot code though I have managed to change stuff in WordPress files and other things, changing fonts and spacing and colors but more by trial and error and not by actually knowing what I'm doing, and often failing, but more often succeeding).

So my suggestions are for making your app more accessible and understandable to everybody--unless that isn't your aim with YOUR app.  And it is yours and that means you can do whatever you want with it.  You just need to decide who want this app to be for.  And, that should be on the webpage--"This product is geared for...."--the same way the difficulty of auto-repair and DIY projects are often marked.  If someone doesn't know how to change the oil on their car, they won't be able to fix the transmission.  If someone doesn't have a lot of experience with third-party apps and extensions and stuff, they may very well have problems with your app.  Even with a lot of experience, I have had some trouble with it.  And when people have trouble with an app or product, whether it is their fault or a failure to find the proper user info or an actual product defect, they'll go and give the thing 0 or 1 star in feedback ratings and user forums and all kinds of place and that type of behavior will lower the number of people who will end up using your app.  Just a big meal for thought.

**Comment by tjmarkham** [comment]
This isn't a forum to air your grievances or pontificate about your views on common human behavior. It's a area to report issues with a program. It's my fault for engaging you, but I'm going to clean this thread up so that it remains on topic for the initial issue you reported. 

If you have specific issues with Win10 Widgets (like the hard drive issue) I'm happy to help you with those.

Thanks again for your feedback.

**Comment by CaseyKazan** [comment]
It's not a demand, TJ.  It's a matter of clarity.  And, while
      Rainmeter won't change, and you apparently won't match their
      quirk, you could, after the first use of the word "widget"
      include in parens the following: (what Rainmeter calls a "skin") 
      Simple.  It's a suggestion, not a demand.  It's a matter of not
      confusing users.  I found that very confusing in trying to
      navigate the Rainmeter menu and I'm sure lots of others do, too.  
      Like I just posted in the forum, it's your app, you can gear it to
      whomever you want, but you have to understand what each level of
      user needs to be able to use an app.
    
    
    On 8/10/2016 10:28 AM, TJ Markham
      wrote:
    
    
      
        Lastly, and I'm posting this in the Rainmeter forum, one way
          or another, either THEY need to rename "skins" to "widgets",
          or YOU need to start identifying the individual components in
          win10widgets as skins the way that Rainmeter does. YOU do it
          correctly, they don't, but it need to be coordinated to avoid
          confusion. That's like one company calling a car's manual gear
          shift lever the "transmission modifying device." You see what
          I mean? So, either you get them to call the components in the
          skins (whether illustro or Win10 Widgets or whatever)
          "widgets" and not "skins" OR you start calling your actual
          widgets "skins" (ick, but one or the other).
      
      Please do not post on the Rainmeter forum; they are not going
        to stop calling them skins.
      In the same vein, I'm not going to stop calling them widgets.
      No one needs to do anything... You're taking this a
        little too seriously. These aren't companies, these are just
        regular people making free software tools for other to use. You
        didn't buy anything, so you don't really have any room to make
        these types of demands. If you don't like it, you don't have to
        use it.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tjmarkham/win10widgets","title":"tjmarkham/win10widgets","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tjmarkham/win10widgets"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tjmarkham in #20: \u003e Lastly, and I'm posting this in the Rainmeter forum, one way or another, either THEY need to rename \"skins\" to \"widgets\", or YOU need to start identifying the individual components in win10widgets as skins the way that Rainmeter does. YOU do it correctly, they don't, but it need to be coordinated to avoid confusion. That's like one company calling a car's manual gear shift lever the \"transmission modifying device.\" You see what I mean? So, either you get them to call the components in the skins (whether illustro or Win10 Widgets or whatever) \"widgets\" and not \"skins\" OR you start calling your actual widgets \"skins\" (ick, but one or the other).\r\n\r\nPlease do not post on the Rainmeter forum; they are not going to stop calling them skins.\r\n\r\nIn the same vein, I'm not going to stop calling them widgets.\r\n\r\nNo one *needs* to do anything... You're taking this a little too seriously. These aren't companies, these are just regular people making free software tools for other to use. You didn't buy anything, so you don't really have any room to make these types of demands. If you don't like it, you don't have to use it."}],"action":{"name":"View Issue","url":"https://github.com/tjmarkham/win10widgets/issues/20#issuecomment-238940761"}}}

**Comment by tjmarkham** [comment]
I'm done engaging you on this. As I said, I'm going to clean up this thread. If you want, please feel free to email me at win10widgets@gmail.com with these types of concerns. The issue tracker is for specific issues with the actual program. Not to express your concerns with how the website is worded or things of that nature.

**Comment by tjmarkham** [comment]
I've saved this thread locally on my machine (in a PDF). I'm going to clean it up now to reflect the original issue you reported.

**Comment by tjmarkham** [comment]
This thread got off topic so it is now locked to prevent future off topic discussions. Any concerns/suggestions not related to specific widgets in Win10 Widgets should be directed to win10widgets@gmail.com (e.g. suggestions for the website, etc.).
