### ISSUE TITLE
Tiny disk skin doesn't utilize width/length of skin

### ISSUE THREAD

**Issue by Saltystew** [tjmarkham/win10widgets#27]
The length/width of the tiny disk skin is nice for keep things uniform, but the graph could utilize much more of the space if you just put the Disk label information on the other side of the graph and maybe made it vertical or something. 

Just looks odd, takes up more space than it needs to if it's just going to be a square.

**Comment by tjmarkham** [comment]
Thanks for the feedback!

I did that on purpose, the graphs are that size to match the graphs you get in the side-bar of the performance tab of the task manager. Open the task manager and drag the dividing line of the side-bar to the right; you'll see that everything remains the same size (the graphs don't stretch to fit the space). The widget background is that size to keep everything uniform.

If your looking for a wider graph in a small form factor, the "small" size of the widget is what you're looking for.

**Comment by tjmarkham** [comment]
Related: I'm going to make "thin" versions of all the widgets in the future, so you'll be able to choose a "tiny-thin" size for the performance widgets that will have less "empty space" on the right.

**Comment by Saltystew** [comment]
Alright then.
