### ISSUE TITLE
Lock doesn't work, just reloads stuff.

### ISSUE THREAD

**Issue by chickenweed** [tjmarkham/win10widgets#4]
I just downloaded Win10 widgets about half an hour ago and I'm having trouble with the Lock.  I've watched the help video and it seems pretty straightforward -- left-click the lock and it changes to a locked icon and prevents the widgets from being moved.

However, when I left-click the lock it just reloads all the widgets.  It reloads the weather and starts all the cpu, etc., meters from scratch, as if the skin were freshly loaded.  And it never changes from an unlocked icon to a locked one.  I've tried changing sizes in case the .ini was broken for one of them, but they all work the same way.

I've unloaded all of my other skins but that didn't help.  I've tried double-clicking, right-clicking and going through all the options... everything I can think of but it just won't work.  I'm stumped.

**Comment by tjmarkham** [comment]
The reloading behavior is normal. Rainmeter needs to reload the settings file that stores the "DisableDragging" setting which results in the skins being refreshed as well.

That's strange that the lock button isn't doing anything though. Before I get into troubleshooting options, would you mind letting me know what version of Rainmeter you're using? That way I can install the same version and see if I can replicate the issue.

You can find your Rainmeter version by doing the following: right-click the Rainmeter "raindrop" icon in the notification area (i.e. system tray) and click "About." Next, click the "Version" tab and let me know what that top line says.

For example, mine says: `4.0.0 beta r2613 64-bit (Jul  6 2016)`

**Comment by chickenweed** [comment]
Hi, thanks for responding.

My version is 4.0.0 beta r2618 64-bit (Jul 13 2016) running on Windows 10 Pro 64-bit (build 10586).

I'm also running into this exact same issue on the other system I have this installed on, which is all exactly the same except for being 32-bit.  

Both OS & Rainmeter installs are pretty fresh and haven't been tinkered with very much.

**Comment by tjmarkham** [comment]
Okay, I just installed that version on the same OS and I'm not seeing the issue. Did you select the "Portable installation" when you installed Rainmeter by any chance? Or did you go with the "Standard installation (recommended)" when you installed Rainmeter?

I might need you to attach some Rainmeter files so I can look at them, but before we do that, I'd like to have you try to disable and enable dragging through the Rainmeter application and see if that works. If it does let me know, and try using the lock widget again and see if that resolves the issue.

To enable/disable dragging using Rainmeter, right-click the Rainmeter "raindrop" icon in the notification area (i.e. system tray), select "Skins," and click "Disable dragging." If there's a check-mark next to "Disable dragging" it means it's enabled (i.e. the skins _wont_ be able to be dragged). If there's no check-mark it means the skins _can_ be dragged.

**Comment by chickenweed** [comment]
It is the standard installation on both systems.

Checking "disable dragging" does work -- toggling it on does prevent dragging as it should.  I loaded the Lock and it came up showing as locked but I still wasn't able to use it to toggle that setting.  I unchecked "disable dragging" but the Lock skin still showed as locked -- when I clicked it and everything reloaded, the graphic changed to show it as being unlocked and then it wouldn't toggle back to the locked state.

So the Rainmeter setting does work, and the Lock skin will show its correct state on being refreshed or reloaded, but the actual functionality of the Lock skin itself still doesn't work for me.

**Comment by tjmarkham** [comment]
Okay I see the problem now.

Let's see if we can fix this. I just uploaded an updated version of the **Lock-small.ini** file that I'd like you to try out:

- Go to the file on GitHub here: https://github.com/tjmarkham/win10widgets/blob/master/Win10%20Widgets/Lock/Lock-Small.ini
- Find the "Raw" button. It's in the header of the "code" area to the right.
- Right-click the "Raw" button and click "Save link as..."
- In the save dialog, navigate to:

`C:\Users\[Your_User_Name]\Documents\Rainmeter\Skins\Win10 Widgets\Lock`
- Save the file. When Windows asks if you want to replace the current file, click "Yes."
- Right-click the "Lock" widget and click "Refresh skin."

Let me know if that works. If it does I can make similar changes to the other files that are affected.

**Comment by chickenweed** [comment]
That fixed it, thanks.

And I love your work on this skin, by the way.  Very nice job.

**Comment by tjmarkham** [comment]
Awesome! I'll work on implementing the solution across the other files.

Thanks for the compliments! Glad you like it :)

**Comment by tjmarkham** [comment]
Just updated the other two files. For future reference here are links:
- https://github.com/tjmarkham/win10widgets/blob/master/Win10%20Widgets/%40Resources/background.ini
- https://github.com/tjmarkham/win10widgets/blob/master/Win10%20Widgets/LayoutSwitcher/LayoutSwitcher-Small.ini

You can follow the same instructions above if you want to replace them. I'll work on getting an official release out soon.
