### ISSUE TITLE
Weather connection error

### ISSUE THREAD

**Issue by Sigmanor** [tjmarkham/win10widgets#61]
Very often I see this error, the city set correctly.
![](http://i.imgur.com/P7QWY8y.png)

Log.
![](http://i.imgur.com/Q3sTliB.png)

**Comment by kendoori** [comment]
Having same issue

**Comment by stevehoek** [comment]
Same here.   Are the Yahoo API's having trouble again?
It would be nice to switch to weather.com or wxdata

**Comment by memece3** [comment]
Same issue.. Just started Couple weeks ago.
