### ISSUE TITLE
[Question] How to track additional drives?

### ISSUE THREAD

**Issue by bkuhl** [tjmarkham/win10widgets#79]
I didn't see anything in the HardDrive .ini files for instructions on how to track additional drives.  Is that an option?  If so, how?

**Comment by bkuhl** [comment]
The way to accomplish this is to duplicate the "HardDrive" directory within `C:\Users\[MY_USER]\Documents\Rainmeter\Skins\Win10 Widgets` and replace the `Disk=` value within `HardDrive-Large.ini` with the additional drive letter you want to monitor (.e.g - `Disk=D:`).

By default it uses the drive where these files exist.

**Comment by IanBP** [comment]
If you mean using only one widget, right click the widget and select "Select from available drives." from there, it will have available drives in white text on the widget itself.

If you mean monitoring more than one drive at one time, the way I did it was make copies of the HardDrive folder in the "C:\...\Rainmeter\Skins\Win10 Widgets\" directory and select "Refresh all" in the Rainmeter settings. From there, you can load the skins and have them view different drives.

**Comment by bkuhl** [comment]
Yep, this worked for me.
