### ISSUE TITLE
Question about the weather widget.

### ISSUE THREAD

**Issue by bdaddio** [tjmarkham/win10widgets#9]
Hello,

I've installed these awesome windows 10 widgets but I can't for the life of me figure out how to change the city in the weather widget.  Everytime I put in a postal code, a city, province or country it always reverts back to Dublin, DUB.

Would appreciate any help.  Thanks

**Comment by tjmarkham** [comment]
Sorry you're having trouble!

Hmm that's strange, I haven't heard of that issue before. You can try replacing your current **Weather-ExtraLarge.ini** file with one that I just updated earlier today. Check out this comment here for instructions: https://github.com/tjmarkham/win10widgets/issues/7#issuecomment-236367185

Let me know if that works.

**Comment by bdaddio** [comment]
Worked like a charm thank you.

Also, sorry for the noob question but is there anywhere you can point me to how to use the spotify widget? I have an account and would like to try out the widget but can't figure out how to get spotify to point to it.

Thanks again

**Comment by tjmarkham** [comment]
Awesome, glad it worked! Yeah, check out this comment on Reddit for info about the Spotify plugin: https://www.reddit.com/r/Rainmeter/comments/4s6nik/win10_widgets_widgets_that_become_part_of_windows/d59p0xy

**Comment by bdaddio** [comment]
Thanks again will give it a go!
